name: MOEX Signal Bot

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name Install dependencies
        run: |
          python -m pip install -- upgrade pip
          pip install -r moex/requirements.txt

      - name Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN}}
          CHAT_ID: $ {{secrets.CHAT_ID}}
        run: |
          cd moex
          python moex_main.py
